name: Security Audit
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  autid:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Audit
        run: npm audit